name: Lint, Format, Test

on:
  push:
    branches: [ "main", "lab-one-pr", "lab-two-pr"]
  pull_request:
    branches: [ "main", "lab-one-pr", "lab-two-pr"]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Spotless
        run: mvn spotless:check

      - name: Run Checkstyle
        run: mvn checkstyle:check
        
      - name: Run Tests
        run: mvn test
